import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";

import { AppProvider } from "@/providers/app.provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
const locale="fr"
  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <AppProvider locale={locale}>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
